### ISSUE TITLE
Patient poses can be changed by player

### ISSUE THREAD

**Issue by smkrexus** [smkrexus/GGJ2024-UE5#22]
Patient is always in the same pose
Find a way to change player poses during gameplay (think about both outside mini-game and during)
Don't need to be too intricate with high degree of  freedom, maybe some on-screen buttons
Poses can be used as part of a requirement for joint interaction

**Comment by germainelee** [comment]
On-screen buttons inspo [source](https://snowbreak.gg/massage-guide/)

![Image](https://github.com/user-attachments/assets/aeadfa71-3c93-405d-be29-14007214c7ad)
