### ISSUE TITLE
crosshair is drawn below gauge in pressure minigame

### ISSUE THREAD

**Issue by germainelee** [smkrexus/GGJ2024-UE5#43]
Currently the crosshair is behind the confirmation Arcs and Gauge. Cursor should always be drawn above everything else.

![image](https://github.com/user-attachments/assets/aa6d382a-467b-41d9-a77c-b42e7576c8d2)

**Comment by germainelee** [comment]
![image](https://github.com/user-attachments/assets/e282f0b8-659a-42ee-9beb-ad2017b353ff)
 
- [ ] crosshair should be drawn above confirmation "braces"
- [ ] crosshair is drawn above gauge

**Comment by smkrexus** [comment]
![Image](https://github.com/user-attachments/assets/1d3668a9-3a41-4f4a-9184-8b5888d61211)
you want to try handling this?
