### ISSUE TITLE
Revise Review UI to Bar

### ISSUE THREAD

**Issue by germainelee** [smkrexus/GGJ2024-UE5#59]
To draw the connection between 3 Stars and review %, revise ui to be similar to image below

![image](https://github.com/user-attachments/assets/d3123c0b-954c-4e6a-be4a-b79d165b4f49)

_Originally posted by @germainelee in https://github.com/smkrexus/GGJ2024-UE5/issues/6#issuecomment-2411169763_

**Comment by smkrexus** [comment]
![Image](https://github.com/user-attachments/assets/fe84c4bc-e1a2-43a0-89ad-e931de8462f4)
