### ISSUE TITLE
Spawn obstacle for injured joints

### ISSUE THREAD

**Issue by germainelee** [smkrexus/GGJ2024-UE5#8]
Currently there's no challenge during the move-mouse-pointer-to-green-dot minigame so the obstacle will serve as a challenge for injured joints. the obstacles could be a POINT, A STRING OF POINTS, or A LINE

**Comment by smkrexus** [comment]
use size of pressure target for injured joints challenge instead. simpler and more intuitive

**Comment by smkrexus** [comment]
no longer valid, gameplay is different for pressure mode now

**Comment by germainelee** [comment]
see above https://github.com/smkrexus/GGJ2024-UE5/issues/8#issuecomment-2384746335
